kind: pipeline
name: merchant_api

clone:
  disable: true

steps:
  - name: docker-merchant
    image: appleboy/drone-ssh:1.6.5-linux-amd64
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/merchant_service
        - git checkout -- .
        - git fetch
        - git checkout dev
        #- git checkout -- .
        - git pull origin dev
        #- git pull
        - go mod tidy
        - docker-compose -f merchant/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=merchant_service" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/merchant merchant/merchant.go
        - docker build -t merchant_service -f merchant/Dockerfile .
        - docker-compose -f merchant/docker-compose.yml up -d
    when:
      branch:
        - dev
      event:
        - push
        
trigger:
  branch:
    - dev
